druid-public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIEopNjvUKeGp5M+aKc+yY/a/PDYKI/O96U04PFFjmZ+ukTf00H0uU7mexYyLx0C6+opdKKdNJfdC94x+2fAdP8CAwEAAQ==


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://221.228.197.214:3306/mytestdelete?useSSL=false
    username: root
    password: KxU08WZP6Rwi+Ux7fMeUqMU27ojzMdkaicuxkmWeXbiVRX2az/WtAvfep3EavFetTC1hV6Ssve4PzGt//XPZmw==
    druid:
      connection-properties: config.decrypt=true;config.decrypt.key=${druid-public-key}

server:
  port: 8082