spring:
  profiles:
    active: @springProfileActive@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          statement-executable-sql-log-enable: true
          db-type: mysql
        wall:
          enabled: true
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 0
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      rscoreToCamelCase: true